### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by scottopolis** [shprink/ionic2-webpack-boilerplate#1]
I did $ git clone, then npm install, then npm run devserver. Got these errors:

ERROR in multi main
Module not found: Error: Cannot resolve module 'es6-shim' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'zone.js' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'reflect-metadata' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'angular2/angular2' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate
 @ multi main

ERROR in ./lib/data/data.module.js
Module build failed: Cannot resolve module 'angular2/angular2' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/data
    Required in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/data/data.module.js
 @ ./lib/index.js 25:20-49

ERROR in ./lib/account/account.module.js
Module build failed: Cannot resolve module 'angular2/angular2' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/account
    Required in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/account/account.module.js
 @ ./lib/tabs/tabs.module.js 26:23-59

ERROR in ./lib/chat/chat.module.js
Module build failed: Cannot resolve module 'angular2/angular2' in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/chat
    Required in /Users/scottopolis/Documents/Apps/ionic2-webpack-ES6-boilerplate/lib/chat/chat.module.js
 @ ./lib/chats/chats.module.js 25:20-50

**Comment by shprink** [comment]
yep you are running an old npm version I guess:

![image](https://cloud.githubusercontent.com/assets/1388706/10645179/02e5bafc-77f2-11e5-8978-bb939617fada.png)

**Comment by scottopolis** [comment]
Just updated, getting same errors.

npm -v
3.3.8

node -v
v4.2.1

I also tried npm cache clean, with no success.

**Comment by shprink** [comment]
it is working fine on my end. 

```
# Remove node_modules when you re-install it is safer.
rm -rf node_modules/
npm install
```

**Comment by chr1gu** [comment]
Got the same error with a fresh installation. Running on Win10, Npm v.3.7.3, Node v.v4.3.1. Looks like there are missing dependencies.

**Comment by shprink** [comment]
This repo is kinda old, it need to be updated. If you happen to make it
work with the ionic 2 beta version please make a PR
